spring.application.name=wander

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_db?sslmode=disable
spring.datasource.username=wander
spring.datasource.password=wander
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect